### ISSUE TITLE
一公司路牌数

### ISSUE THREAD

**Issue by wangxy0327** [Fangml718/jiushi_vehiclelog#3]
问一下目前55 61 147 597 134 60 103 90 桥三 20 28 868 934 25 135 155有多少路牌？

**Comment by Fangml718** [comment]
等工作日再看

**Comment by wangxy0327** [comment]
> 等工作日再看

那后天留意一下吧

**Comment by Fangml718** [comment]
30 20 14 23 20 15 17 27 16 22 20 22 22 27 18 16

**Comment by wangxy0327** [comment]
> 

55路最近我看都出了29台？是不是真有没出满的情况？

**Comment by Fangml718** [comment]
> 55路最近我看都出了29台？是不是真有没出满的情况？

8点多的时候我记得是出29，现在是30

**Comment by wangxy0327** [comment]
> > 55路最近我看都出了29台？是不是真有没出满的情况？
> 
> 8点多的时候我记得是出29，现在是30

Z0A出了3个还是4个？

**Comment by Fangml718** [comment]
> 

这个没看，得上海交通上牌照一个个查

**Comment by wangxy0327** [comment]
再问一下99和8路都是13路牌吗？758还是14吗？15 19 20 23 24 876 36 751 960 875 123 有多少路牌？

**Comment by Fangml718** [comment]
> 再问一下99和8路都是13路牌吗？758还是14吗？15 19 20 23 24 876 36 751 960 875 123 有多少路牌？

99路15，8路13，758路14，后面的18 21 22 25 20 23 22 19 14 16 18

**Comment by wangxy0327** [comment]
36确定22路牌吗？我看最近一些S0R还在24路上跑

**Comment by Fangml718** [comment]
> 36确定22路牌吗？我看最近一些S0R还在24路上跑

36路计划22路牌，但今天只出了20个车

**Comment by wangxy0327** [comment]
今天是双休日，问一下66区间 960 60 723 842 桥三 59 406 15 19 20 13 23 24 36 939 8 22 28 868 934 6 14 25 135 155双休日多少路牌？

**Comment by wangxy0327** [comment]
> 

25路确定是13个吗？再问以下66路是17个还是19个？749/124是9个吗？876 37 55多少？

**Comment by Fangml718** [comment]
25路确定13，66路17，749路10，124路8，876路19，37路17，55路18。在 2023年2月11日，17:58，wangxy0327 ***@***.***> 写道：﻿


25路确定是13个吗？再问以下66路是17个还是19个？749/124是9个吗？876 37 55多少？

**Comment by wangxy0327** [comment]
> 25路确定13，66路17，749路10，124路8，876路19，37路17，55路18。在 2023年2月11日，17：58，wangxy0327 ***@***.***> 写道： 25路确定是13个吗？再问以下66路是17个还是19个？749/124是9个吗？876 37 55多少？ - 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您发表了评论。消息 ID：***@***.***>

168还是9个吗？

**Comment by Fangml718** [comment]
168路7。


> 在 ***@***.*** 写道：
>

**Comment by wangxy0327** [comment]
问一下今天55 758 60 103 723 桥三 36路牌有没有出满？如果没的话出了多少？
另外37现在是28路牌吗？

**Comment by Fangml718** [comment]
> 问一下今天55 758 60 103 723 桥三 36路牌有没有出满？如果没的话出了多少？ 另外37现在是28路牌吗？

60路15出14，723路18出15，36路22出20，其他都出满的，37路28路牌

**Comment by wangxy0327** [comment]
> > 问一下今天55 758 60 103 723 桥三 36路牌有没有出满？如果没的话出了多少？ 另外37现在是28路牌吗？
> 
> 60路15出14，723路18出15，36路22出20，其他都出满的，37路28路牌

90路出满了吗？

**Comment by Fangml718** [comment]
> > > 问一下今天55 758 60 103 723 桥三 36路牌有没有出满？如果没的话出了多少？ 另外37现在是28路牌吗？
> > 
> > 
> > 60路15出14，723路18出15，36路22出20，其他都出满的，37路28路牌
> 
> 90路出满了吗？

90路出满的
