### ISSUE TITLE
110 528户口

### ISSUE THREAD

**Issue by bmybgm** [Fangml718/jiushi_vehiclelog#6]
110户口目前还是都S2Y，528户口目前还是都S2Z吗？

**Comment by Fangml718** [comment]
是的，这俩配车对换户口没动在 2023年2月7日，14:35，bmybgm ***@***.***> 写道：﻿
110户口目前还是都S2Y，528户口目前还是都S2Z吗？

**Comment by Fangml718** [comment]
是的，这俩配车对换户口没动

**Comment by bmybgm** [comment]
BTW，730 929路牌目前多少，另外S0R0123-0129 0174-0177目前户口哪里？

**Comment by bmybgm** [comment]
还有122多少路牌看下，谢谢

**Comment by Fangml718** [comment]
> BTW，730 929路牌目前多少，另外S0R0123-0129 0174-0177目前户口哪里？

730路20，929路24，那些S0R目前户口还都是浦东11

**Comment by Fangml718** [comment]
> 还有122多少路牌看下，谢谢

12

**Comment by bmybgm** [comment]
五公司四车队今天恢复路牌？711 963 1600 1610 宝山8 21 23 28 31 81 82 83 90路牌都恢复了？

**Comment by Fangml718** [comment]
五公司公众号说711/963/宝山8/21/23恢复了，一共增加25个车，我这里没有过往的路牌数所以不清楚具体情况在 2023年2月10日，17:45，bmybgm ***@***.***> 写道：﻿
五公司四车队今天恢复路牌？711 963 1600 1610 宝山8 21 23 28 31 81 82 83 90路牌都恢复了？

**Comment by bmybgm** [comment]
> 

所以这些线路路牌数量可以说下嘛，谢谢

**Comment by Fangml718** [comment]
> > 
> 
> 所以这些线路路牌数量可以说下嘛，谢谢

14 35 3 3 21 18 18 3 9 5 6 2 4

**Comment by bmybgm** [comment]
问下今天98 04 206 845 159 728 701 813 宝山17 宝山29 108 65 40 46547 762 853 110 528 551 702 705 741 745 850 862路牌数量，谢谢

**Comment by bmybgm** [comment]
另外看看今天43 89 171 205路牌，谢谢

**Comment by Fangml718** [comment]
> 问下今天98 04 206 845 159 728 701 813 宝山17 宝山29 108 65 40 46547 762 853 110 528 551 702 705 741 745 850 862路牌数量，谢谢

| 线路   | 路牌数 |
|------|-----|
| 98   | 10  |
| 04   | 10  |
| 206  | 23  |
| 845  | 21  |
| 159  | 26  |
| 728  | 22  |
| 701  | 15  |
| 813  | 24  |
| 宝山17 | 4   |
| 宝山29 | 20  |
| 108  | 22  |
| 65   | 16  |
| 40   | 20  |
| 46   | 24  |
| 547  | 13  |
| 762  | 15  |
| 853  | 10  |
| 110  | 24  |
| 528  | 27  |
| 551  | 18  |
| 702  | 21  |
| 705  | 18  |
| 741  | 23  |
| 745  | 11  |
| 850  | 13  |
| 862  | 14  |

**Comment by Fangml718** [comment]
> 另外看看今天43 89 171 205路牌，谢谢

| 线路  | 路牌数 |
|-----|-----|
| 43  | 30  |
| 89  | 26  |
| 171 | 15  |
| 205 | 19  |

**Comment by bmybgm** [comment]
目前闵行车队 49路车队各多少路牌，谢谢

**Comment by Fangml718** [comment]
> 目前闵行车队 49路车队各多少路牌，谢谢

| 线路    | 路牌数 |
|-------|-----|
| 143   | 14  |
| 881   | 10  |
| 徐闵    | 42  |
| 江川3   | 5   |
| 闵东    | 7   |
| 闵吴    | 7   |
| 闵行16  | 6   |
| 闵行29  | 12  |
| 闵行30  | 6   |
| 闵行35  | 7   |
| 闵行40  | 5   |
| 闵行41  | 11  |
| 49    | 21  |
| 157   | 12  |
| 704   | 7   |
| 704B  | 6   |
| 714   | 14  |
| 718   | 13  |
| 720   | 20  |
| 864   | 4   |
| 1203  | 2   |
| 1204  | 2   |
| 1204B | 1   |

**Comment by bmybgm** [comment]
今天五公司58 185 767 51 52 160 552 118 133 713 502 132 812 760 834 839 172 1607 1609 719 811 宝山5 宝山6 宝山7 宝山10 宝山12 宝山15 宝山16 宝山18 宝山25 宝山30 宝山84 宝山92 宝山93 宝山95，二公司92 87，四公司869 933 926 42 41 973 781 456 17 96 736 104 桥一 隧道二 730 929 974 715 975 64 733 930 932 浦东97多少路牌，谢谢？

**Comment by bmybgm** [comment]
再加1606，谢谢

**Comment by Fangml718** [comment]
> 今天五公司58 185 767 51 52 160 552 118 133 713 502 132 812 760 834 839 172 1607 1609 719 811 宝山5 宝山6 宝山7 宝山10 宝山12 宝山15 宝山16 宝山18 宝山25 宝山30 宝山84 宝山92 宝山93 宝山95，二公司92 87，四公司869 933 926 42 41 973 781 456 17 96 736 104 桥一 隧道二 730 929 974 715 975 64 733 930 932 浦东97多少路牌，谢谢？

| 线路   | 路牌数 |
|------|-----|
| 58   | 22  |
| 185  | 20  |
| 767  | 12  |
| 51   | 31  |
| 52   | 22  |
| 160  | 18  |
| 552  | 21  |
| 118  | 25  |
| 133  | 17  |
| 713  | 28  |
| 502  | 11  |
| 132  | 15  |
| 812  | 29  |
| 760  | 11  |
| 834  | 2   |
| 839  | 5   |
| 172  | 20  |
| 1607 | 7   |
| 1609 | 3   |
| 719  | 12  |
| 811  | 9   |
| 宝山5  | 10  |
| 宝山6  | 11  |
| 宝山7  | 9   |
| 宝山10 | 17  |
| 宝山12 | 2   |
| 宝山15 | 16  |
| 宝山16 | 14  |
| 宝山18 | 8   |
| 宝山25 | 11  |
| 宝山30 | 6   |
| 宝山84 | 3   |
| 宝山92 | 6   |
| 宝山93 | 6   |
| 宝山95 | 7   |
| 92   | 28  |
| 87   | 26  |
| 869  | 24  |
| 933  | 29  |
| 926  | 17  |
| 42   | 13  |
| 41   | 24  |
| 973  | 18  |
| 781  | 11  |
| 456  | 16  |
| 17   | 18  |
| 96   | 18  |
| 736  | 12  |
| 104  | 15  |
| 大桥一线 | 13  |
| 隧道二线 | 11  |
| 730  | 20  |
| 929  | 24  |
| 974  | 25  |
| 715  | 16  |
| 975  | 23  |
| 64   | 20  |
| 733  | 13  |
| 930  | 13  |
| 932  | 19  |
| 浦东97 | 22  |
| 1606 | 8   |
| 151  | 17  |

**Comment by wangxy0327** [comment]
想问一下728户口除了S2Z以外还有什么车？S2Y-0141-0146 S2W-0316 W0G-0058-0062 S2V-0137-0141户口在哪里？S2Z-1284 1285户口在1604还是813？

**Comment by Fangml718** [comment]
> 想问一下728户口除了S2Z以外还有什么车？S2Y-0141-0146 S2W-0316 W0G-0058-0062 S2V-0137-0141户口在哪里？S2Z-1284 1285户口在1604还是813？

728除S2Z外还有S2Y-0141-0144；
S2Y-0145：十车队备车；
S2Y-0146：十一车队备车；
S2W-0316：十二车队备车；
W0G-0058-0062：04（并不跑04）；
S2V-0137-0141：宝山22；
S2Z-1284-1285：813

**Comment by wangxy0327** [comment]
> > 想问一下728户口除了S2Z以外还有什么车？S2Y-0141-0146 S2W-0316 W0G-0058-0062 S2V-0137-0141户口在哪里？S2Z-1284 1285户口在1604还是813？
> 
> 728除S2Z外还有S2Y-0141-0144; S2Y-0145：十车队备车; S2Y-0146：十一车队备车; S2W-0316：十二车队备车; W0G-0058-0062：04（并不跑04）; S2V-0137-0141：宝山22; S2Z-1284-1285：813

S2V-0129 0130十车队备车吗？04户口10个吗，其中另5个是啥？十二车队户口划备车的有哪些？132路的L0B有划十二车队备车吗？申崇五线有几个路牌？118户口27个Z0A吗？

**Comment by Fangml718** [comment]
> > > 想问一下728户口除了S2Z以外还有什么车？S2Y-0141-0146 S2W-0316 W0G-0058-0062 S2V-0137-0141户口在哪里？S2Z-1284 1285户口在1604还是813？
> > 
> > 
> > 728除S2Z外还有S2Y-0141-0144; S2Y-0145：十车队备车; S2Y-0146：十一车队备车; S2W-0316：十二车队备车; W0G-0058-0062：04（并不跑04）; S2V-0137-0141：宝山22; S2Z-1284-1285：813
> 
> S2V-0129 0130十车队备车吗？04户口10个吗，其中另5个是啥？十二车队户口划备车的有哪些？132路的L0B有划十二车队备车吗？申崇五线有几个路牌？118户口27个Z0A吗？

是的，十车队备车；
04除了W0G外还有S0K-1063/1065/1114-1116；
十二车队备车5个：S2W-0316/S2Y-0640/S8D-0037/Z0A-0558/L9E-0026；
无；
申崇五线12个路牌，并且今天似乎比昨天加了2个，可能周五加路牌；
118路26个Z0A，0519-0534/0536-0542/0555-0557，0535户口133

**Comment by Fangml718** [comment]
> 还有5个S0K户口是五车队备？

是的

**Comment by wangxy0327** [comment]
今天是双休日，上午看一下40 65 108 762 853 887 58 68 78 151 210 767 959 963 宝山8/21/23 845 110 528 551 702 165 705 741 51 719 宝山10/25 116 160 宝山1 159 701 728 813 118 132 133 502 713 760 812路牌数，谢谢！

**Comment by Fangml718** [comment]
> 今天是双休日，上午看一下40 65 108 762 853 887 58 68 78 151 210 767 959 963 宝山8/21/23 845 110 528 551 702 165 705 741 51 719 宝山10/25 116 160 宝山1 159 701 728 813 118 132 133 502 713 760 812路牌数，谢谢！

| 线路    | 路牌数 |
|-------|-----|
| 40    | 15  |
| 65    | 12  |
| 108   | 16  |
| 762   | 14  |
| 853   | 9   |
| 887   | 5   |
| 58    | 17  |
| 68    | 13  |
| 78    | 15  |
| 151   | 17  |
| 210   | 12  |
| 767   | 9   |
| 959   | 11  |
| 963   | 27  |
| 宝山8路  | 16  |
| 宝山21路 | 15  |
| 宝山23路 | 15  |
| 845   | 16  |
| 110   | 17  |
| 528   | 23  |
| 551   | 16  |
| 702   | 18  |
| 165   | 18  |
| 705   | 15  |
| 741   | 20  |
| 51    | 27  |
| 719   | 12  |
| 宝山10路 | 15  |
| 宝山25路 | 11  |
| 116   | 22  |
| 160   | 16  |
| 宝山1路  | 15  |
| 159   | 22  |
| 701   | 14  |
| 728   | 19  |
| 813   | 21  |
| 118   | 21  |
| 132   | 14  |
| 133   | 15  |
| 502   | 10  |
| 713   | 22  |
| 760   | 10  |
| 812   | 26  |

**Comment by wangxy0327** [comment]
> > 今天是双休日，上午看一下[40 65 108 762 853](tel:40 65 108 762 853) [887 58 68 78 151 210](tel:887 58 68 78 151 210) [767 959 963](tel:767 959 963) 宝山8/21/23 [845 110 528 551 702](tel:845 110 528 551 702) [165 705 741 51 719](tel:165 705 741 51 719) 宝山[10/25 116 160](tel:10/25 116 160) 宝山[1 159 701 728 813 118](tel:1 159 701 728 813 118) [132 133 502 713 760](tel:132 133 502 713 760) 812路牌数，谢谢！
> 
> 线路	路牌数
> 40	15
> 65	12
> 108	16
> 762	14
> 853	9
> 887	5
> 58	17
> 68	13
> 78	15
> 151	17
> 210	12
> 767	9
> 959	11
> 963	27
> 宝山8路	16
> 宝山21路	15
> 宝山23路	15
> 845	16
> 110	17
> 528	23
> 551	16
> 702	18
> 165	18
> 705	15
> 741	20
> 51	27
> 719	12
> 宝山10路	15
> 宝山25路	11
> 116	22
> 160	16
> 宝山1路	15
> 159	22
> 701	14
> 728	19
> 813	21
> 118	21
> 132	14
> 133	15
> 502	10
> 713	22
> 760	10
> 812	26

185 727 宝山37 745 850 862 宝山20 宝山7 宝山29也看一下谢谢。另外151双休日路牌实际根工作日一样？

**Comment by Fangml718** [comment]
> > > 今天是双休日，上午看一下[40 65 108 762 853](tel:40 65 108 762 853) [887 58 68 78 151 210](tel:887 58 68 78 151 210) [767 959 963](tel:767 959 963) 宝山8/21/23 [845 110 528 551 702](tel:845 110 528 551 702) [165 705 741 51 719](tel:165 705 741 51 719) 宝山[10/25 116 160](tel:10/25 116 160) 宝山[1 159 701 728 813 118](tel:1 159 701 728 813 118) [132 133 502 713 760](tel:132 133 502 713 760) 812路牌数，谢谢！
> > 
> > 
> > 线路	路牌数
> > 40	15
> > 65	12
> > 108	16
> > 762	14
> > 853	9
> > 887	5
> > 58	17
> > 68	13
> > 78	15
> > 151	17
> > 210	12
> > 767	9
> > 959	11
> > 963	27
> > 宝山8路	16
> > 宝山21路	15
> > 宝山23路	15
> > 845	16
> > 110	17
> > 528	23
> > 551	16
> > 702	18
> > 165	18
> > 705	15
> > 741	20
> > 51	27
> > 719	12
> > 宝山10路	15
> > 宝山25路	11
> > 116	22
> > 160	16
> > 宝山1路	15
> > 159	22
> > 701	14
> > 728	19
> > 813	21
> > 118	21
> > 132	14
> > 133	15
> > 502	10
> > 713	22
> > 760	10
> > 812	26
> 
> 185 727 宝山37 745 850 862 宝山20 宝山7 宝山29也看一下谢谢。另外151双休日路牌实际根工作日一样？

| 线路    | 路牌数 |
|-------|-----|
| 185   | 16  |
| 727   | 7   |
| 宝山37路 | 4   |
| 745   | 9   |
| 850   | 12  |
| 862   | 11  |
| 宝山20路 | 3   |
| 宝山7路  | 8   |
| 宝山29路 | 17  |

151双休日和工作日路牌数相同

**Comment by bmybgm** [comment]
看下46 172 87 92 徐闵 49 703 218 189 189区间 729 747 763 762 143 43 89 205 171 731 735 732 770双休日路牌数量，谢谢

**Comment by bmybgm** [comment]
是162，不是762，前面打错不好意思

**Comment by Fangml718** [comment]
> 看下46 172 87 92 徐闵 49 703 218 189 189区间 729 747 763 762 143 43 89 205 171 731 735 732 770双休日路牌数量，谢谢

| 线路    | 路牌数 |
|-------|-----|
| 46    | 19  |
| 172   | 18  |
| 87    | 16  |
| 92    | 19  |
| 徐闵线   | 29  |
| 49    | 17  |
| 703   | 15  |
| 218   | 23  |
| 189   | 22  |
| 189区间 | 8   |
| 729   | 15  |
| 747   | 20  |
| 763   | 12  |
| 162   | 9   |
| 143   | 11  |
| 43    | 18  |
| 89    | 19  |
| 205   | 14  |
| 171   | 13  |
| 731   | 12  |
| 735   | 22  |
| 732   | 18  |
| 770   | 13  |

**Comment by bmybgm** [comment]
43路牌就18？？？这么少？

**Comment by Fangml718** [comment]
是的。在 2023年2月18日，22:44，bmybgm ***@***.***> 写道：﻿
43路牌就18？？？这么少？

**Comment by bmybgm** [comment]
看下今天和20日宝山31路路牌数量，谢谢

**Comment by Fangml718** [comment]
> 看下今天和20日宝山31路路牌数量，谢谢

今天10

**Comment by Fangml718** [comment]
> 看下今天和20日宝山31路路牌数量，谢谢

19号10，20号11

**Comment by wangxy0327** [comment]
问一下78 68 116 51 963多少正加路牌谢谢

**Comment by Fangml718** [comment]
> 问一下78 68 116 51 963多少正加路牌谢谢

| 线路  | 正路牌 | 加路牌 |
|-----|-----|-----|
| 78  | 15  | 6   |
| 68  | 13  | 7   |
| 116 | 22  | 8   |
| 51  | 27  | 4   |
| 963 | 27  | 8   |

**Comment by bmybgm** [comment]
徐闵42路牌里面，加路牌多少

**Comment by Fangml718** [comment]
> 徐闵42路牌里面，加路牌多少

正32加10

**Comment by wangxy0327** [comment]
问一下今天五公司四车队 八车队 十一车队今天多少路牌谢谢

**Comment by Fangml718** [comment]
> 问一下今天五公司四车队 八车队 十一车队今天多少路牌谢谢

| 线路    | 路牌数 |
|-------|-----|
| 1600  | 3   |
| 1606  | 8   |
| 1610  | 3   |
| 711   | 10  |
| 841   | 8   |
| 963   | 27  |
| 宝山21路 | 15  |
| 宝山23路 | 15  |
| 宝山28路 | 2   |
| 宝山31路 | 10  |
| 宝山33路 | 3   |
| 宝山4路  | 2   |
| 宝山81路 | 5   |
| 宝山82路 | 6   |
| 宝山83路 | 2   |
| 宝山88路 | 2   |
| 宝山8路  | 16  |
| 宝山90路 | 3   |
| 508   | 6   |
| 51    | 27  |
| 719   | 12  |
| 811   | 9   |
| 883   | 11  |
| 吴淞滨江线 | 3   |
| 宝山10路 | 15  |
| 宝山25路 | 11  |
| 宝山32路 | 7   |
| 宝山5路  | 10  |
| 宝山7路  | 8   |
| 宝山86路 | 5   |
| 宝山87路 | 5   |
| 宝山89路 | 3   |
| 宝山91路 | 7   |
| 宝山95路 | 7   |
| 1602  | 5   |
| 1603  | 6   |
| 1607  | 7   |
| 1609  | 2   |
| 172   | 18  |
| 834   | 2   |
| 839   | 5   |
| 宝山12路 | 2   |
| 宝山13路 | 1   |
| 宝山14路 | 5   |
| 宝山15路 | 14  |
| 宝山16路 | 12  |
| 宝山18路 | 8   |
| 宝山2路  | 9   |
| 宝山30路 | 6   |
| 宝山3路  | 9   |
| 宝山6路  | 14  |
| 宝山84路 | 3   |
| 宝山92路 | 6   |
| 宝山93路 | 6   |
| 宝山9路  | 4   |
