### ISSUE TITLE
一四公司开学路牌及户口问题

### ISSUE THREAD

**Issue by wangxy0327** [Fangml718/jiushi_vehiclelog#7]
想问一下四公司六、九车队和十车队有没有恢复路牌？具体数量是多少？609多少路牌？

**Comment by Fangml718** [comment]
> 想问一下四公司六、九车队和十车队有没有恢复路牌？具体数量是多少？609多少路牌？

这个要等到早上看

**Comment by wangxy0327** [comment]
> > 想问一下四公司六、九车队和十车队有没有恢复路牌？具体数量是多少？609多少路牌？
> 
> 这个要等到早上看

那上午留意一下吧

**Comment by Fangml718** [comment]
| 线路   | 路牌数 |
|------|-----|
| 徐川   | 29  |
| 浦东17 | 21  |
| 浦东21 | 20  |
| 申川   | 25  |
| 67   | 13  |
| 94   | 21  |
| 858  | 16  |
| 947  | 24  |
| 1205 | 3   |
| 1206 | 3   |
| 长征1  | 9   |
| 510  | 24  |
| 849  | 16  |
| 912  | 15  |
| 937  | 32  |
| 951  | 16  |
| 962  | 9   |
| 609  | 14  |

**Comment by wangxy0327** [comment]
上述线路明天如果有加路牌的话记得再提一下谢谢！
另外问一下68 78 210 767 959 821 宝山19/85 51 116 136 856 748 1250 1251现在多少路牌？

**Comment by Fangml718** [comment]
> 上述线路明天如果有加路牌的话记得再提一下谢谢！ 另外问一下68 78 210 767 959 821 宝山19/85 51 116 136 856 748 1250 1251现在多少路牌？

| 线路   | 路牌数 |
|------|-----|
| 68   | 20  |
| 78   | 21  |
| 210  | 17  |
| 767  | 12  |
| 959  | 13  |
| 821  | 4   |
| 宝山19 | 4   |
| 宝山85 | 3   |
| 51   | 24  |
| 116  | 30  |
| 136  | 17  |
| 856  | 17  |
| 748  | 17  |
| 1250 | 9   |
| 1251 | 6   |

**Comment by wangxy0327** [comment]
明天上午继续留意一下四公司今天提到的上述线路有没有加路牌？
另外还有四公司824 927 二车队 三车队 628 630 632 七车队 八车队，五公司160 552和一公司19 751 758路牌数量，谢谢

**Comment by Fangml718** [comment]
> 明天上午继续留意一下四公司今天提到的上述线路有没有加路牌？ 另外还有四公司824 927 45 911 二车队 三车队 628 630 632 七车队 八车队，五公司160 552和一公司19 751 758路牌数量，谢谢

| 线路   | 路牌数 |
|------|-----|
| 徐川   | 34  |
| 浦东17 | 21  |
| 浦东21 | 20  |
| 申川   | 32  |
| 67   | 15  |
| 94   | 22  |
| 858  | 16  |
| 947  | 24  |
| 1205 | 3   |
| 1206 | 3   |
| 长征1  | 9   |
| 510  | 27  |
| 849  | 16  |
| 912  | 15  |
| 937  | 33  |
| 951  | 19  |
| 962  | 9   |
| 609  | 16  |
| 68   | 20  |
| 78   | 21  |
| 210  | 17  |
| 767  | 12  |
| 959  | 13  |
| 821  | 4   |
| 宝山19 | 4   |
| 宝山85 | 3   |
| 51   | 31  |
| 116  | 30  |
| 136  | 19  |
| 856  | 18  |
| 748  | 17  |
| 1250 | 9   |
| 1251 | 6   |
| 824  | 28  |
| 927  | 16  |
| 45   | 15  |
| 911  | 22  |
| 41   | 24  |
| 104  | 15  |
| 734  | 8   |
| 933  | 29  |
| 973  | 18  |
| 大桥一线 | 13  |
| 隧道二线 | 11  |
| 11   | 10  |
| 17   | 18  |
| 26   | 5   |
| 96   | 18  |
| 456  | 16  |
| 736  | 12  |
| 781  | 11  |
| 805  | 3   |
| 869  | 24  |
| 隧道八线 | 10  |
| 628  | 11  |
| 630  | 11  |
| 632  | 16  |
| 715  | 16  |
| 730  | 20  |
| 929  | 24  |
| 974  | 25  |
| 975  | 23  |
| 浦东97 | 22  |
| 18   | 25  |
| 42   | 13  |
| 64   | 20  |
| 146  | 14  |
| 733  | 13  |
| 866  | 3   |
| 926  | 17  |
| 930  | 13  |
| 932  | 19  |
| 1222 | 2   |
| 160  | 18  |
| 552  | 21  |
| 19   | 21  |
| 751  | 19  |
| 758  | 14  |

**Comment by wangxy0327** [comment]
607是15路牌吗？615 浦东11 65 66多少？

**Comment by Fangml718** [comment]
> 607是15路牌吗？615 浦东11 65 66多少？

| 线路   | 路牌数 |
|------|-----|
| 607  | 14  |
| 615  | 19  |
| 浦东11 | 19  |
| 浦东65 | 6   |
| 浦东66 | 14  |

**Comment by wangxy0327** [comment]
孙桥1是12吗？浦东15是18吗？138 624 浦东13 合庆2多少？

**Comment by Fangml718** [comment]
> 孙桥1是12吗？浦东15是18吗？138 624 浦东13 合庆2多少？

| 线路   | 路牌数 |
|------|-----|
| 孙桥1  | 11  |
| 浦东15 | 18  |
| 138  | 14  |
| 624  | 16  |
| 浦东13 | 7   |
| 合庆2  | 3   |

**Comment by wangxy0327** [comment]
想问一下824S2V户口是0056-0084吗？S0P-0148户口还在三车队吗？L9D-0085 S0P-0151-0154 0169 S0S-0500-0502户口在哪里?浦东13/65/66和628户口有哪些？

**Comment by Fangml718** [comment]
> 想问一下824S2V户口是0056-0084吗？S0P-0148户口还在三车队吗？L9D-0085 S0P-0151-0154 0169 S0S-0500-0502户口在哪里?浦东13/65/66和628户口有哪些？

是；是，户口456的；96（猜测顶替W0F-0278代教），730，浦东97，浦东97，929，929，长征1，长征1，长征1；浦东13：L9D-0019/0118~0123/0130，浦东65：L9D-0017/0124~0129，W0F-0358，浦东66：L9D-0131~0144/0151/W0F-0360，628：L9D-0029/0145~0150/0152~0155

**Comment by wangxy0327** [comment]
> > 想问一下824S2V户口是0056-0084吗？S0P-0148户口还在三车队吗？L9D-0085 S0P-0151-0154 0169 S0S-0500-0502户口在哪里?浦东13/65/66和628户口有哪些？
> 
> 是；是，户口456的；96（猜测顶替W0F-0278代教），730，浦东97，浦东97，929，929，长征1，长征1，长征1；浦东13：L9D-0019/0118-0123/0130，浦东65：L9D-0017/0124-0129/W0F-0358，浦东66：L9D-0131-0144/0151/W0F-0360，628：L9D-0029/0145-0150/0152~0155

L9D-0018 0030 S0M-0079 0080户口在哪里？桥一和隧二L0B户口有哪些？六车队W0H户口有变化吗？一公司一车队S2V-0028-0055户口有变化吗？

**Comment by Fangml718** [comment]
> 

630，合庆2，973，41；
桥一：0017/0019/0020/0029-0040，隧二：0021-0028；
六车队W0H无变化；
0028：597
0029-0037：66区间
0038：597
0039-0041：66区间
0042-0047：66
0048-0055：597

**Comment by Fangml718** [comment]
> > > 
> > 
> > 
> > 630，合庆2，973，41； 桥一：0017/0019/0020/0029-0040，隧二：0021-0028； 六车队W0H无变化； 0028：597 0029-0037：66区间 0038：597 0039-0041：66区间 0042-0047：66 0048-0055：597
> 
> L0B-0018在哪？L9D-0020 0096 0097也是合庆2路吗？

L0B-0018户口973；是的

**Comment by wangxy0327** [comment]
问一下五公司78路户口具体有哪些车？另外S0R-0235和二车队W0G户口在哪些线路？

**Comment by Fangml718** [comment]
> 问一下五公司78路户口具体有哪些车？另外S0R-0235和二车队W0G户口在哪些线路？

78路：S0R-0052/54/57/0189，S0S-0396/0399/0401/0457，Z0A-0679-0689/0712/0713；
S0R-0235户口是二车队备车；
W0G-0021-0035：185
W0G-0036-0039：宝山38
W0G-0040-0043：185
W0G-0044：二车队备车
W0G-0045：185
W0G-0046：宝山38
W0G-0056：959
W0G-0057：二车队备车

**Comment by wangxy0327** [comment]
宝山38户口有10个？151户口是不是15个S0R？另外58户口有哪些？

**Comment by Fangml718** [comment]
> 宝山38户口有10个？151户口是不是15个S0R？另外58户口有哪些？

是的，但是W0G应该是不出的；是的，0191-0205；S2Y-0006/W1F-0125-0144/0146

**Comment by wangxy0327** [comment]
> > 宝山38户口有10个？151户口是不是15个S0R？另外58户口有哪些？
> 
> 是的，但是W0G应该是不出的;是的，0191-0205;S2Y-0006/W1F-0125-0144/0146

宝山38W0G有两辆给151加路牌，还有一些在185。另外S2Y-0005户口还在821吗？

**Comment by wangxy0327** [comment]
> > > 宝山38户口有10个？151户口是不是15个S0R？另外58户口有哪些？
> > 
> > 
> > 是的，但是W0G应该是不出的;是的，0191-0205;S2Y-0006/W1F-0125-0144/0146
> 
> 宝山38W0G有两辆给151加路牌，0046在58，还有一些在185。另外S2Y-0005户口还在821吗？

**Comment by Fangml718** [comment]
> > > > 宝山38户口有10个？151户口是不是15个S0R？另外58户口有哪些？
> > > 
> > > 
> > > 是的，但是W0G应该是不出的;是的，0191-0205;S2Y-0006/W1F-0125-0144/0146
> > 
> > 
> > 宝山38W0G有两辆给151加路牌，0046在58，还有一些在185。另外S2Y-0005户口还在821吗？

是的

**Comment by wangxy0327** [comment]
问一下现在108户口还有S0R吗？S0R-0056户口在40还是一车队备车？十车队S0S户口有变过吗？Z0A-0558户口在118还是133？

**Comment by Fangml718** [comment]
> 问一下现在108户口还有S0R吗？S0R-0056户口在40还是一车队备车？十车队S0S户口有变过吗？Z0A-0558户口在118还是133？

S0R-0188户口还是108；S0R-0056户口一车队备车；最近应该都没变；十二车队备车

**Comment by wangxy0327** [comment]
> > 问一下现在108户口还有S0R吗？S0R-0056户口在40还是一车队备车？十车队S0S户口有变过吗？Z0A-0558户口在118还是133？
> 
> S0R-0188户口还是108；S0R-0056户口一车队备车；最近应该都没变；十二车队备车

S0S-0362-0378都在701？S0R-0181-0186一车队备车？L9E-0026备车在哪里？

**Comment by Fangml718** [comment]
> > > 问一下现在108户口还有S0R吗？S0R-0056户口在40还是一车队备车？十车队S0S户口有变过吗？Z0A-0558户口在118还是133？
> > 
> > 
> > S0R-0188户口还是108；S0R-0056户口一车队备车；最近应该都没变；十二车队备车
> 
> S0S-0362-0378都在701？S0R-0181-0186一车队备车？L9E-0026备车在哪里？

是的，0379也在；是的；十二车队备车

**Comment by wangxy0327** [comment]
今天上午看一下四公司一车队 二车队 17 96 736 869 六车队 七车队 18 42 64 146 926 930 932 67 94 858 947 长征1 十车队的路牌数，谢谢！

**Comment by wangxy0327** [comment]
还有一公司55 61 99 597 79 134 751 875 538 220 723 874 942 90 537 870 405

**Comment by Fangml718** [comment]
> 还有一公司55 61 99 597 79 134 751 875 538 220 123 874 942 90 537 870 405 21 33

| 线路  | 路牌数 |
|-----|-----|
| 55  | 18  |
| 61  | 15  |
| 99  | 11  |
| 597 | 19  |
| 79  | 13  |
| 134 | 14  |
| 751 | 11  |
| 875 | 13  |
| 538 | 13  |
| 220 | 15  |
| 123 | 14  |
| 874 | 15  |
| 942 | 16  |
| 90  | 20  |
| 537 | 21  |
| 870 | 15  |
| 405 | 14  |
| 21  | 21  |
| 33  | 10  |

**Comment by wangxy0327** [comment]
> > 还有一公司[55 61 99 597 79 134](tel:55 61 99 597 79 134) [751 875 538 220 123](tel:751 875 538 220 123) [874 942 90 537 870](tel:874 942 90 537 870) [405 21 33](tel:405 21 33)
> 
> 线路	路牌数
> 55	18
> 61	15
> 99	11
> 597	19
> 79	13
> 134	14
> 751	11
> 875	13
> 538	13
> 220	15
> 123	14
> 874	15
> 942	16
> 90	20
> 537	21
> 870	15
> 405	14
> 21	21
> 33	10

47 70 875 四公司456 781 四车队 五车队 733多少？

**Comment by Fangml718** [comment]
> > > 还有一公司[55 61 99 597 79 134](tel:55 61 99 597 79 134) [751 875 538 220 123](tel:751 875 538 220 123) [874 942 90 537 870](tel:874 942 90 537 870) [405 21 33](tel:405 21 33)
> > 
> > 
> > 线路	路牌数
> > 55	18
> > 61	15
> > 99	11
> > 597	19
> > 79	13
> > 134	14
> > 751	11
> > 875	13
> > 538	13
> > 220	15
> > 123	14
> > 874	15
> > 942	16
> > 90	20
> > 537	21
> > 870	15
> > 405	14
> > 21	21
> > 33	10
> 
> 47 70 875 四公司456 781 四车队 五车队 733多少？

| 线路    | 路牌数 |
|-------|-----|
| 47    | 11  |
| 70    | 10  |
| 875   | 13  |
| 456   | 14  |
| 781   | 8   |
| 184   | 6   |
| 607   | 13  |
| 609   | 14  |
| 615   | 16  |
| 624   | 14  |
| 629   | 5   |
| 浦东14路 | 8   |
| 浦东15路 | 16  |
| 1014  | 2   |
| 628   | 9   |
| 630   | 9   |
| 632   | 15  |
| 合庆2路  | 3   |
| 孙桥1路  | 9   |
| 浦东11路 | 17  |
| 浦东13路 | 7   |
| 浦东65路 | 6   |
| 浦东66路 | 13  |
| 浦东76路 | 3   |
| 733   | 11  |

**Comment by wangxy0327** [comment]
还有537 854 100 115

**Comment by Fangml718** [comment]
> 一司双休日路牌看来跟工作日正特路牌总和不完全一样，有的线路加或抽了。97路是8个路牌吗？137 746 6有多少？

| 线路  | 路牌数 |
|-----|-----|
| 97  | 8   |
| 137 | 10  |
| 746 | 13  |
| 6   | 12  |
| 537 | 21  |
| 854 | 16  |
| 100 | 11  |
| 115 | 15  |

**Comment by wangxy0327** [comment]
问一下四公司剩余的W0F以及L9D-0001-0030户口分别在哪里？谢谢！

**Comment by Fangml718** [comment]
> 问一下四公司剩余的W0F以及L9D-0001-0030户口分别在哪里？谢谢！

W0F户口全部632没有更新；
L9D：
0001-0002：609
0003：浦东15
0004-0005：609
0006-0008：632
0009：609
0010-0013：632
0014：609
0015-0016：632
0017：浦东65
0018：630
0019：浦东13
0020：合庆2
0021-0022：184
0023-0027：632
0028：624
0029：628
0030：合庆2

**Comment by wangxy0327** [comment]
浦东15路剩余户口是0071-0084 0113-0116吗？0117是外高桥2路？W0H-0292-0301 0325-0334户口在哪里？S8C-0001-0020在615吗？0021在609？S8D哪些在浦东14和609？S0Q-0001 0016户口在哪里？S0S-0458户口在96？

**Comment by wangxy0327** [comment]
浦东15路剩余户口是0071-0084 0113-0116吗？0117是外高桥2路？W0H-0292-0301 0325-0334户口在哪里？S8C-0001-0020在615吗？0021在609？S8D哪些在浦东14和609？S0Q-0001 0016户口在哪里？S0S-0458户口在96？

**Comment by Fangml718** [comment]
> 浦东15路剩余户口是0071-0084 0113-0116吗？0117是外高桥2路？W0H-0292-0301 0325-0334户口在哪里？S8C-0001-0020在615吗？0021在609？S8D哪些在浦东14和609？S0Q-0001 0016户口在哪里？S0S-0458户口在96？

0071-0084户口还是之前的607，0113-0116是浦东15，0117是外高桥2；
W0H-0292-0301徐川，0325-0330浦东21，0331-0334申川；
S8C-0002户口浦东14；
S8D-0022户口615，0030户口609，其他浦东14；
S0Q-0001/0016户口都是26；
S0S-0485户口805

**Comment by wangxy0327** [comment]
第二天上午一公司三车队和四车队路牌看一下，谢谢！

**Comment by Fangml718** [comment]
> 第二天上午一公司三车队和四车队路牌看一下，谢谢！

| 线路   | 路牌数 |
|------|-----|
| 1201 | 4   |
| 1218 | 3   |
| 1226 | 2   |
| 1228 | 1   |
| 1255 | 4   |
| 1256 | 3   |
| 134  | 20  |
| 538  | 18  |
| 559  | 6   |
| 70   | 14  |
| 751  | 19  |
| 758  | 14  |
| 79   | 16  |
| 80   | 5   |
| 875  | 16  |
| 960  | 14  |
| 103  | 17  |
| 142  | 5   |
| 195  | 1   |
| 220  | 21  |
| 577  | 7   |
| 60   | 13  |
| 723  | 18  |
| 842  | 18  |
| 874  | 20  |

**Comment by wangxy0327** [comment]
> > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> 
> 线路	路牌数
> 1201	4
> 1218	3
> 1226	2
> 1228	1
> 1255	4
> 1256	3
> 134	20
> 538	18
> 559	6
> 70	14
> 751	19
> 758	14
> 79	16
> 80	5
> 875	16
> 960	14
> 103	17
> 142	5
> 195	1
> 220	21
> 577	7
> 60	13
> 723	18
> 842	18
> 874	20

看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？

**Comment by Fangml718** [comment]
> > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > 
> > 
> > 线路	路牌数
> > 1201	4
> > 1218	3
> > 1226	2
> > 1228	1
> > 1255	4
> > 1256	3
> > 134	20
> > 538	18
> > 559	6
> > 70	14
> > 751	19
> > 758	14
> > 79	16
> > 80	5
> > 875	16
> > 960	14
> > 103	17
> > 142	5
> > 195	1
> > 220	21
> > 577	7
> > 60	13
> > 723	18
> > 842	18
> > 874	20
> 
> 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？

是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15

**Comment by wangxy0327** [comment]
> > > 
> > 
> > 
> > 630，合庆2，973，41; 桥一：0017/0019/0020/0029-0040，隧二：0021-0028; 六车队W0H无变化; 0028：597 0029-0037：66区间 0038：597 0039-0041：66区间 0042-0047：66 0048-0055：597
> 
> L0B-0018在哪？L9D-0020 0096 0097也是合庆2路吗？

问一下桥一户口除了L0B以外还有什么车？S0M-0079 0080 S0P-0178 0179户口在哪里？

**Comment by wangxy0327** [comment]
> > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > 
> > > 
> > > 线路 路牌数 1201 4 1218 3 1226 2 1228 1 1255 4 1256 3 134 20 538 18 559 6 70 14 751 19 758 14 79 16 80 5 875 16 960 14 103 17 142 5 195 1 220 21 577 7 60 13 723 18 842 18 874 20
> > 
> > 
> > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> 
> 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15

723一辆S0S-1053长期在220，47的S2V-0055今天给66区间跑了

**Comment by Fangml718** [comment]
> > > > 
> > > 
> > > 
> > > 630，合庆2，973，41; 桥一：0017/0019/0020/0029-0040，隧二：0021-0028; 六车队W0H无变化; 0028：597 0029-0037：66区间 0038：597 0039-0041：66区间 0042-0047：66 0048-0055：597
> > 
> > 
> > L0B-0018在哪？L9D-0020 0096 0097也是合庆2路吗？
> 
> 问一下桥一户口除了L0B以外还有什么车？S0M-0079 0080 S0P-0178 0179户口在哪里？

桥一户口下还有S0R-0030；S0M-0079户口973，0080户口41，S0P-0178/0179户口933

**Comment by wangxy0327** [comment]
> > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > 
> > > 
> > > 线路	路牌数
> > > 1201	4
> > > 1218	3
> > > 1226	2
> > > 1228	1
> > > 1255	4
> > > 1256	3
> > > 134	20
> > > 538	18
> > > 559	6
> > > 70	14
> > > 751	19
> > > 758	14
> > > 79	16
> > > 80	5
> > > 875	16
> > > 960	14
> > > 103	17
> > > 142	5
> > > 195	1
> > > 220	21
> > > 577	7
> > > 60	13
> > > 723	18
> > > 842	18
> > > 874	20
> > 
> > 
> > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> 
> 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15

36 24 23 21 37今天出满了吗？没出满的话实际多少？

**Comment by wangxy0327** [comment]
另外能方便问一下55 61 66 66区间 220 90 21 25 20 19 868 14 6分别多少正路牌和加路牌吗？

**Comment by Fangml718** [comment]
> 另外能方便问一下55 61 66 66区间 220 90 21 25 20 19 868 14 6分别多少正路牌和加路牌吗？

| 线路   | 正路牌 | 加路牌 |
|------|-----|-----|
| 55   | 22  | 8   |
| 61   | 15  | 5   |
| 66   | 19  | 6   |
| 66区间 | 11  | 4   |
| 19   | 13  | 8   |
| 20   | 17  | 5   |
| 21   | 24  | 14  |
| 90   | 20  | 7   |
| 14   | 12  | 8   |
| 6    | 14  | 6   |
| 868  | 15  | 7   |
| 25   | 13  | 14  |
| 220  | 15  | 6   |

**Comment by Fangml718** [comment]
> 另外能方便问一下55 61 66 66区间 220 90 21 25 20 19 868 14 6分别多少正路牌和加路牌吗？

| 线路   | 正路牌 | 加路牌 |
|------|-----|-----|
| 55   | 22  | 8   |
| 61   | 15  | 5   |
| 66   | 19  | 6   |
| 66区间 | 11  | 4   |
| 220  | 15  | 6   |
| 90   | 20  | 7   |
| 21   | 24  | 14  |
| 25   | 13  | 14  |
| 20   | 17  | 5   |
| 19   | 13  | 8   |
| 868  | 15  | 7   |
| 14   | 12  | 8   |
| 6    | 14  | 6   |

**Comment by Fangml718** [comment]
> > > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > > 
> > > > 
> > > > 线路	路牌数
> > > > 1201	4
> > > > 1218	3
> > > > 1226	2
> > > > 1228	1
> > > > 1255	4
> > > > 1256	3
> > > > 134	20
> > > > 538	18
> > > > 559	6
> > > > 70	14
> > > > 751	19
> > > > 758	14
> > > > 79	16
> > > > 80	5
> > > > 875	16
> > > > 960	14
> > > > 103	17
> > > > 142	5
> > > > 195	1
> > > > 220	21
> > > > 577	7
> > > > 60	13
> > > > 723	18
> > > > 842	18
> > > > 874	20
> > > 
> > > 
> > > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> > 
> > 
> > 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15
> 
> 36 24 23 21 37今天出满了吗？没出满的话实际多少？

都出满了

**Comment by wangxy0327** [comment]
> 另外能方便问一下55 61 66 66区间 220 90 21 25 20 19 868 14 6分别多少正路牌和加路牌吗？

597 13 23 24 15 36 939 37 746 8 22 28 934 135 155 99 79 60 874 942 537 桥三也看一下谢谢

**Comment by wangxy0327** [comment]
> > > > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > > > 
> > > > > 
> > > > > 线路 路牌数 1201 4 1218 3 1226 2 1228 1 1255 4 1256 3 134 20 538 18 559 6 70 14 751 19 758 14 79 16 80 5 875 16 960 14 103 17 142 5 195 1 220 21 577 7 60 13 723 18 842 18 874 20
> > > > 
> > > > 
> > > > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> > > 
> > > 
> > > 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15
> > 
> > 
> > 36 24 23 21 37今天出满了吗？没出满的话实际多少？
> 
> 都出满了

36出满了？我看今天24还有36的S0R在跑

**Comment by Fangml718** [comment]
> > > > > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > > > > 
> > > > > > 
> > > > > > 线路 路牌数 1201 4 1218 3 1226 2 1228 1 1255 4 1256 3 134 20 538 18 559 6 70 14 751 19 758 14 79 16 80 5 875 16 960 14 103 17 142 5 195 1 220 21 577 7 60 13 723 18 842 18 874 20
> > > > > 
> > > > > 
> > > > > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> > > > 
> > > > 
> > > > 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15
> > > 
> > > 
> > > 36 24 23 21 37今天出满了吗？没出满的话实际多少？
> > 
> > 
> > 都出满了
> 
> 36出满了？我看今天24还有36的S0R在跑

36路22出22

**Comment by Fangml718** [comment]
| 线路   | 正路牌 | 加路牌 |
|------|-----|-----|
| 597  | 19  | 4   |
| 13   | 13  | 11  |
| 23   | 13  | 12  |
| 24   | 13  | 7   |
| 15   | 13  | 5   |
| 36   | 13  | 9   |
| 939  | 12  | 6   |
| 37   | 17  | 11  |
| 746  | 13  | 8   |
| 8    | 8   | 5   |
| 22   | 9   | 4   |
| 28   | 12  | 8   |
| 934  | 15  | 7   |
| 135  | 10  | 8   |
| 155  | 9   | 7   |
| 99   | 11  | 4   |
| 79   | 14  | 2   |
| 60   | 10  | 3   |
| 874  | 15  | 5   |
| 942  | 16  | 5   |
| 537  | 21  | 5   |
| 大桥三线 | 16  | 0   |

**Comment by wangxy0327** [comment]
147 134 758是4个加路牌吗？另外538 751 70 123 960 723 876正加路牌也看一下谢谢

**Comment by Fangml718** [comment]
> 147 134 758是4个加路牌吗？另外538 751 70 123 960 723 876正加路牌也看一下谢谢

| 线路  | 正路牌 | 加路牌 |
|-----|-----|-----|
| 147 | 10  | 4   |
| 134 | 14  | 6   |
| 758 | 10  | 4   |
| 538 | 13  | 5   |
| 751 | 12  | 7   |
| 70  | 11  | 3   |
| 123 | 15  | 3   |
| 960 | 12  | 2   |
| 723 | 14  | 4   |
| 876 | 19  | 4   |

**Comment by wangxy0327** [comment]
> > > > > > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > > > > > 
> > > > > > > 
> > > > > > > 线路 路牌数 1201 4 1218 3 1226 2 1228 1 1255 4 1256 3 134 20 538 18 559 6 70 14 751 19 758 14 79 16 80 5 875 16 960 14 103 17 142 5 195 1 220 21 577 7 60 13 723 18 842 18 874 20
> > > > > > 
> > > > > > 
> > > > > > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> > > > > 
> > > > > 
> > > > > 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15
> > > > 
> > > > 
> > > > 36 24 23 21 37今天出满了吗？没出满的话实际多少？
> > > 
> > > 
> > > 都出满了
> > 
> > 
> > 36出满了？我看今天24还有36的S0R在跑
> 
> 36路22出22

昨天没发现36抢了13路的一辆S2Y，今天发现也在线。问一下今天13路24个路牌有没有出满？

**Comment by Fangml718** [comment]
> > > > > > > > > 第二天上午一公司三车队和四车队路牌看一下，谢谢！
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 线路 路牌数 1201 4 1218 3 1226 2 1228 1 1255 4 1256 3 134 20 538 18 559 6 70 14 751 19 758 14 79 16 80 5 875 16 960 14 103 17 142 5 195 1 220 21 577 7 60 13 723 18 842 18 874 20
> > > > > > > 
> > > > > > > 
> > > > > > > 看来60路真抽过路牌了，我看今天还是没有出满只有12辆吧？另外今天723 79 758 47实际出了多少？
> > > > > > 
> > > > > > 
> > > > > > 是的，60路目前出12辆。723路16/18，79路16/16，758路14/14，47路14/15
> > > > > 
> > > > > 
> > > > > 36 24 23 21 37今天出满了吗？没出满的话实际多少？
> > > > 
> > > > 
> > > > 都出满了
> > > 
> > > 
> > > 36出满了？我看今天24还有36的S0R在跑
> > 
> > 
> > 36路22出22
> 
> 昨天没发现36抢了13路的一辆S2Y，今天发现也在线。问一下今天13路24个路牌有没有出满？

出满了

**Comment by Fangml718** [comment]
> 问一下1201 1218 577 168 559是有2个加路牌吗，1258和142是一个加路牌吗？另外问一下875 80 103 842 554 823 59 406 124 749 870有多少正加路牌，谢谢！

| 线路   | 正路牌 | 加路牌 |
|------|-----|-----|
| 1201 | 2   | 2   |
| 1218 | 1   | 2   |
| 577  | 5   | 2   |
| 168  | 7   | 2   |
| 559  | 4   | 2   |
| 1258 | 4   | 1   |
| 142  | 4   | 1   |
| 875  | 13  | 3   |
| 80   | 3   | 2   |
| 103  | 13  | 4   |
| 842  | 11  | 7   |
| 554  | 10  | 0   |
| 823  | 9   | 0   |
| 59   | 19  | 5   |
| 406  | 15  | 3   |
| 124  | 8   | 3   |
| 749  | 10  | 1   |
| 870  | 15  | 6   |

**Comment by wangxy0327** [comment]
问一下90的27路牌和桥三的16路牌有没有出满？

**Comment by Fangml718** [comment]
> 问一下90的27路牌和桥三的16路牌有没有出满？

都出满了

**Comment by wangxy0327** [comment]
今天上午看一下868 869 743 822 45 浦西滨江1路双休日路牌数，谢谢！

**Comment by Fangml718** [comment]
> 今天上午看一下868 869 743 822 45 浦西滨江1路双休日路牌数，谢谢！

| 线路     | 路牌数 |
|--------|-----|
| 868    | 15  |
| 869    | 20  |
| 743    | 16  |
| 822    | 14  |
| 45     | 11  |
| 浦西滨江1路 | 8   |

**Comment by wangxy0327** [comment]
> > 今天上午看一下[868 869 743 822 45](tel:868 869 743 822 45) 浦西滨江1路双休日路牌数，谢谢！
> 
> 线路	路牌数
> 868	15
> 869	20
> 743	16
> 822	14
> 45	11
> 浦西滨江1路	8

869双休日居然还加了一块路牌

**Comment by wangxy0327** [comment]
> > 今天上午看一下[868 869 743 822 45](tel:868 869 743 822 45) 浦西滨江1路双休日路牌数，谢谢！
> 
> 线路	路牌数
> 868	15
> 869	20
> 743	16
> 822	14
> 45	11
> 浦西滨江1路	8

问一下822安亭路牌有几块看得出来吗？

**Comment by bmybgm** [comment]
184路目前多少路牌

**Comment by Fangml718** [comment]
> > > 今天上午看一下[868 [869 743 822](tel:869 743 822) 45](tel:[868 869 743 822 45](tel:868 869 743 822 45)) 浦西滨江1路双休日路牌数，谢谢！
> > 
> > 
> > 线路	路牌数
> > 868	15
> > 869	20
> > 743	16
> > 822	14
> > 45	11
> > 浦西滨江1路	8
> 
> 问一下822安亭路牌有几块看得出来吗？

这个看不出来

**Comment by Fangml718** [comment]
> 184路目前多少路牌

6

**Comment by wangxy0327** [comment]
明天上午看一下868（这条顺便看一下几正几加） 869 743 827 828 822 宝山6/9多少路牌，谢谢！

**Comment by Fangml718** [comment]
> 明天上午看一下868（这条顺便看一下几正几加） 869 743 827 828 822 宝山6/9多少路牌，谢谢！

| 线路   | 正路牌 | 加路牌 |
|------|-----|-----|
| 868  | 15  | 7   |
| 869  | 20  | 4   |
| 743  | 16  | 4   |
| 827  | 12  | 2   |
| 828  | 11  | 2   |
| 822  | 14  | 2   |
| 宝山6路 | 14  | 1   |
| 宝山9路 | 4   | 0   |

**Comment by wangxy0327** [comment]
今天早高峰758S0T出来了，问一下是不是14个车出满了？

**Comment by Fangml718** [comment]
> 今天早高峰758S0T出来了，问一下是不是14个车出满了？

出满了

**Comment by wangxy0327** [comment]
问一下今天137路一共出了多少车？谢谢

**Comment by Fangml718** [comment]
> 问一下今天137路一共出了多少车？谢谢

16

**Comment by wangxy0327** [comment]
> > 问一下今天137路一共出了多少车？谢谢
> 
> 16

好吧，可能今天S0T/S有替开的情况。另外今天S0S-0117 0121代跑6路和14路

**Comment by wangxy0327** [comment]
问一下今天1201是不是3个路牌？1218几个？

**Comment by Fangml718** [comment]
> 问一下今天1201是不是3个路牌？1218几个？

1201路3个，1218路1个

**Comment by wangxy0327** [comment]
> > 问一下今天1201是不是3个路牌？1218几个？
> 
> 1201路3个，1218路1个

538今天还是18个路牌吗？

**Comment by Fangml718** [comment]
> > > 问一下今天1201是不是3个路牌？1218几个？
> > 
> > 
> > 1201路3个，1218路1个
> 
> 538今天还是18个路牌吗？

是的
