### ISSUE TITLE
五公司新S0S附属问题

### ISSUE THREAD

**Issue by bmybgm** [Fangml718/jiushi_vehiclelog#8]
Z0A0601-0606户口目前哪里

**Comment by bmybgm** [comment]
另外五公司塔菜确定没报废目前？

**Comment by Fangml718** [comment]
> Z0A0601-0606户口目前哪里

十一车队备车

**Comment by Fangml718** [comment]
> 另外五公司塔菜确定没报废目前？

最近无

**Comment by bmybgm** [comment]
L0B0082 0083户口在1603？

**Comment by Fangml718** [comment]
> L0B0082 0083户口在1603？

是的

**Comment by bmybgm** [comment]
周一白天请注意下，宝山6工作日路牌，如果15的话，看看是不是加路牌是1，谢谢

**Comment by Fangml718** [comment]
> 周一白天请注意下，宝山6工作日路牌，如果15的话，看看是不是加路牌是1，谢谢

是的，14+1

**Comment by bmybgm** [comment]
今天L9E0074在哪条线路，另外Z0A0601-0606 S2Y0146目前情况如何

**Comment by Fangml718** [comment]
> 今天L9E0074在哪条线路，另外Z0A0601-0606 S2Y0146目前情况如何

涉及具体跑什么线路的问题我暂时没有好的查询方法

**Comment by bmybgm** [comment]
> 

L9E0074今天在1603,1603今天没有Z0A0646

**Comment by wangxy0327** [comment]
问一下今天五公司813 701 728 159 839 宝山92 宝山31多少路牌？

**Comment by bmybgm** [comment]
宝山81路牌也看看，谢谢，顺便看看159 728 宝山31加车路牌数量

**Comment by bmybgm** [comment]
W0F-0947今天还跑1600，怎么户口没了

**Comment by Fangml718** [comment]
> W0F-0947今天还跑1600，怎么户口没了

出错了，现在户口的更新还没稳定

**Comment by bmybgm** [comment]
> > W0F-0947今天还跑1600，怎么户口没了
> 
> 出错了，现在户口的更新还没稳定

今天内容太多感觉

**Comment by bmybgm** [comment]
> > W0F-0947今天还跑1600，怎么户口没了
> 
> 出错了，现在户口的更新还没稳定

W0F0947户口确定在1600？

**Comment by Fangml718** [comment]
> > > W0F-0947今天还跑1600，怎么户口没了
> > 
> > 
> > 出错了，现在户口的更新还没稳定
> 
> W0F0947户口确定在1600？

是的，1600

**Comment by Fangml718** [comment]
> 问一下今天五公司813 701 728 159 839 宝山92 宝山31多少路牌？

| 线路    | 正路牌 | 加路牌 |
|-------|-----|-----|
| 813   | 21  | 3   |
| 701   | 14  | 1   |
| 728   | 19  | 3   |
| 159   | 22  | 4   |
| 839   | 7   | 0   |
| 宝山92路 | 7   | 0   |
| 宝山31路 | 10  | 1   |
| 宝山81路 | 5   | 0   |

**Comment by bmybgm** [comment]
L9D0036 0037目前户口哪里

**Comment by bmybgm** [comment]
还有宝山2和81户口看下，谢谢

**Comment by Fangml718** [comment]
> L9D0036 0037目前户口哪里

宝山4路

**Comment by Fangml718** [comment]
> 还有宝山2和81户口看下，谢谢

宝山2路：W0F-0005-0009/0458/0459/0468/0469
宝山81路：L9D-0040/0041，W0F-0399/0400，W8F-0079（跑宝山82）

**Comment by bmybgm** [comment]
> > 还有宝山2和81户口看下，谢谢
> 
> 宝山2路：W0F-0005-0009/0458/0459/0468/0469 宝山81路：L9D-0040/0041，W0F-0399/0400，W8F-0079（跑宝山82）

W0F0057目前户口哪里

**Comment by Fangml718** [comment]
> > > 还有宝山2和81户口看下，谢谢
> > 
> > 
> > 宝山2路：W0F-0005-0009/0458/0459/0468/0469 宝山81路：L9D-0040/0041，W0F-0399/0400，W8F-0079（跑宝山82）
> 
> W0F0057目前户口哪里

1609

**Comment by wangxy0327** [comment]
问一下今天172 1606 1607 宝山5 87多少路牌？

**Comment by Fangml718** [comment]
> 问一下今天159 728 813 172 1606 1607 宝山5 31 87多少路牌？

| 线路    | 路牌数 |
|-------|-----|
| 159   | 22  |
| 728   | 19  |
| 813   | 21  |
| 172   | 18  |
| 1606  | 8   |
| 1607  | 7   |
| 宝山5路  | 10  |
| 宝山31路 | 10  |
| 宝山87路 | 5   |

**Comment by wangxy0327** [comment]
明天早上看一下宝山31 六车队和730的路牌数量谢谢！

**Comment by Fangml718** [comment]
> 明天早上看一下宝山31 六车队和730的路牌数量谢谢！

| 线路    | 路牌数 |
|-------|-----|
| 宝山31路 | 11  |
| 110   | 24  |
| 528   | 27  |
| 551   | 18  |
| 702   | 21  |
| 727   | 7   |
| 宝山37路 | 3   |
| 730   | 24  |

**Comment by wangxy0327** [comment]
> > 明天早上看一下宝山31 六车队和730的路牌数量谢谢！
> 
> 线路	路牌数
> 宝山31路	11
> 110	24
> 528	27
> 551	18
> 702	21
> 727	7
> 宝山37路	3
> 730	24

715 929多少？

**Comment by Fangml718** [comment]
> > > 明天早上看一下宝山31 六车队和730的路牌数量谢谢！
> > 
> > 
> > 线路	路牌数
> > 宝山31路	11
> > 110	24
> > 528	27
> > 551	18
> > 702	21
> > 727	7
> > 宝山37路	3
> > 730	24
> 
> 715 929多少？

715路17，929路27

**Comment by bmybgm** [comment]
974 975 浦东97工作日也看下，谢谢

**Comment by Fangml718** [comment]
> 974 975 浦东97工作日路牌也看下，谢谢

| 线路    | 路牌数 |
|-------|-----|
| 974   | 25  |
| 975   | 23  |
| 浦东97路 | 24  |

**Comment by bmybgm** [comment]
159 728 701 813今天路牌数继续不变？

**Comment by wangxy0327** [comment]
问一下四公司七车队S0P户口有没有变化？（就是说730/929户口下还有没有S0P？）另外Z0A-0423户口在715还是730？

**Comment by Fangml718** [comment]
> 问一下四公司七车队S0P户口有没有变化？（就是说730/929户口下还有没有S0P？）另外Z0A-0423户口在715还是730？

无变化；730

**Comment by bmybgm** [comment]
五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能

**Comment by bmybgm** [comment]
还有十二车队

**Comment by Fangml718** [comment]
> 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能

都没有变化

| 线路    | 路牌数 |
|-------|-----|
| 110   | 24  |
| 528   | 27  |
| 551   | 18  |
| 702   | 21  |
| 727   | 7   |
| 宝山37路 | 3   |
| 701   | 15  |
| 728   | 22  |
| 813   | 24  |
| 宝山17路 | 4   |
| 宝山26路 | 3   |
| 宝山29路 | 20  |
| 宝山36路 | 3   |
| 宝山31路 | 11  |
| 118   | 25  |
| 132   | 15  |
| 133   | 17  |
| 1601  | 2   |
| 1608  | 3   |
| 1611  | 3   |
| 1612  | 2   |
| 502   | 11  |
| 713   | 28  |
| 760   | 11  |
| 812   | 29  |
| 159   | 26  |
| 1604  | 8   |
| 1605  | 5   |

**Comment by wangxy0327** [comment]
明天看一下四公司七车队路牌数量，谢谢！

**Comment by Fangml718** [comment]
> 明天看一下四公司七车队路牌数量，谢谢！

| 线路    | 路牌数 |
|-------|-----|
| 715   | 15  |
| 730   | 18  |
| 929   | 21  |
| 974   | 24  |
| 975   | 22  |
| 浦东97路 | 17  |

**Comment by bmybgm** [comment]
> > 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能
> 
> 都没有变化
> 
> 线路	路牌数
> 110	24
> 528	27
> 551	18
> 702	21
> 727	7
> 宝山37路	3
> 701	15
> 728	22
> 813	24
> 宝山17路	4
> 宝山26路	3
> 宝山29路	20
> 宝山36路	3
> 宝山31路	11
> 118	25
> 132	15
> 133	17
> 1601	2
> 1608	3
> 1611	3
> 1612	2
> 502	11
> 713	28
> 760	11
> 812	29
> 159	26
> 1604	8
> 1605	5

明天白天看看十和十二车队路牌有无变化，谢谢

**Comment by bmybgm** [comment]
S0S1495-1497今天宝山88

**Comment by bmybgm** [comment]
> > > 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能
> > 
> > 
> > 都没有变化
> > 线路	路牌数
> > 110	24
> > 528	27
> > 551	18
> > 702	21
> > 727	7
> > 宝山37路	3
> > 701	15
> > 728	22
> > 813	24
> > 宝山17路	4
> > 宝山26路	3
> > 宝山29路	20
> > 宝山36路	3
> > 宝山31路	11
> > 118	25
> > 132	15
> > 133	17
> > 1601	2
> > 1608	3
> > 1611	3
> > 1612	2
> > 502	11
> > 713	28
> > 760	11
> > 812	29
> > 159	26
> > 1604	8
> > 1605	5
> 
> 明天白天看看十和十二车队路牌有无变化，谢谢

没变化？

**Comment by Fangml718** [comment]
> > > > 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能
> > > 
> > > 
> > > 都没有变化
> > > 线路	路牌数
> > > 110	24
> > > 528	27
> > > 551	18
> > > 702	21
> > > 727	7
> > > 宝山37路	3
> > > 701	15
> > > 728	22
> > > 813	24
> > > 宝山17路	4
> > > 宝山26路	3
> > > 宝山29路	20
> > > 宝山36路	3
> > > 宝山31路	11
> > > 118	25
> > > 132	15
> > > 133	17
> > > 1601	2
> > > 1608	3
> > > 1611	3
> > > 1612	2
> > > 502	11
> > > 713	28
> > > 760	11
> > > 812	29
> > > 159	26
> > > 1604	8
> > > 1605	5
> > 
> > 
> > 明天白天看看十和十二车队路牌有无变化，谢谢
> 
> 没变化？

无变化

**Comment by Fangml718** [comment]
> > > 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能
> > 
> > 
> > 都没有变化
> > 线路	路牌数
> > 110	24
> > 528	27
> > 551	18
> > 702	21
> > 727	7
> > 宝山37路	3
> > 701	15
> > 728	22
> > 813	24
> > 宝山17路	4
> > 宝山26路	3
> > 宝山29路	20
> > 宝山36路	3
> > 宝山31路	11
> > 118	25
> > 132	15
> > 133	17
> > 1601	2
> > 1608	3
> > 1611	3
> > 1612	2
> > 502	11
> > 713	28
> > 760	11
> > 812	29
> > 159	26
> > 1604	8
> > 1605	5
> 
> 明天白天看看十和十二车队路牌有无变化，谢谢

159加到29，701加到17，728加到23

**Comment by bmybgm** [comment]
1604还是8？

**Comment by bmybgm** [comment]
宝山86户口8部？八车队备车E户口没车了？

**Comment by Fangml718** [comment]
> 宝山86户口8部？八车队备车E户口没车了？

是的，L9D-0053-0060户口都是宝山86；是的

**Comment by bmybgm** [comment]
申崇五不会要把路牌加到14？

**Comment by Fangml718** [comment]
> 申崇五不会要把路牌加到14？

今天还是12（周五周一会加2个车，平常是10），看下周会不会变了

**Comment by wangxy0327** [comment]
> > > > 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能
> > > 
> > > 
> > > 都没有变化
> > > 线路	路牌数
> > > 110	24
> > > 528	27
> > > 551	18
> > > 702	21
> > > 727	7
> > > 宝山37路	3
> > > 701	15
> > > 728	22
> > > 813	24
> > > 宝山17路	4
> > > 宝山26路	3
> > > 宝山29路	20
> > > 宝山36路	3
> > > 宝山31路	11
> > > 118	25
> > > 132	15
> > > 133	17
> > > 1601	2
> > > 1608	3
> > > 1611	3
> > > 1612	2
> > > 502	11
> > > 713	28
> > > 760	11
> > > 812	29
> > > 159	26
> > > 1604	8
> > > 1605	5
> > 
> > 
> > 明天白天看看十和十二车队路牌有无变化，谢谢
> 
> 159加到29，701加到17，728加到23

这三条线路明天路牌看一下，谢谢

**Comment by Fangml718** [comment]
> > > > > 五公司六车队 十车队和宝山31路牌数量看看，谢谢，不排除这些有动路牌的可能
> > > > 
> > > > 
> > > > 都没有变化
> > > > 线路	路牌数
> > > > 110	24
> > > > 528	27
> > > > 551	18
> > > > 702	21
> > > > 727	7
> > > > 宝山37路	3
> > > > 701	15
> > > > 728	22
> > > > 813	24
> > > > 宝山17路	4
> > > > 宝山26路	3
> > > > 宝山29路	20
> > > > 宝山36路	3
> > > > 宝山31路	11
> > > > 118	25
> > > > 132	15
> > > > 133	17
> > > > 1601	2
> > > > 1608	3
> > > > 1611	3
> > > > 1612	2
> > > > 502	11
> > > > 713	28
> > > > 760	11
> > > > 812	29
> > > > 159	26
> > > > 1604	8
> > > > 1605	5
> > > 
> > > 
> > > 明天白天看看十和十二车队路牌有无变化，谢谢
> > 
> > 
> > 159加到29，701加到17，728加到23
> 
> 这三条线路明天路牌看一下，谢谢

22 14 19

**Comment by bmybgm** [comment]
工作日正班也是这些吧？

**Comment by bmybgm** [comment]
另外今天宝山10是不是少出了1个路牌

**Comment by Fangml718** [comment]
> 工作日正班也是这些吧？

是的

**Comment by Fangml718** [comment]
> 另外今天宝山10是不是少出了1个路牌

没有，和上周末一样都是15出15

**Comment by wangxy0327** [comment]
527今天多少路牌？

**Comment by Fangml718** [comment]
> 527今天多少路牌？

17

**Comment by bmybgm** [comment]
> > 527今天多少路牌？
> 
> 17

正班14加车3？

**Comment by Fangml718** [comment]
> > > 527今天多少路牌？
> > 
> > 
> > 17
> 
> 正班14加车3？

是的

**Comment by Fangml718** [comment]
> 今天741多少路牌

23

**Comment by wangxy0327** [comment]
今天502多少路牌？

**Comment by Fangml718** [comment]
> 今天502多少路牌？

14

**Comment by Fangml718** [comment]
> 760还是11？ 133还是17？ 713还是28？ 132还是16？

760 12
133 17
713 28
132 16

**Comment by bmybgm** [comment]
760正班11,132正班15？

**Comment by bmybgm** [comment]
十二车队L9E户口看下，谢谢，3-6，16 17，23-27,58-63

**Comment by Fangml718** [comment]
> 760正班11,132正班15？

760 10+2
132 14+2

**Comment by Fangml718** [comment]
> 十二车队L9E户口看下，谢谢，3-6，16 17，23-27,58-63

3-6 760
16-17 1601
23 1612
24 760
25 1612
26 十二车队备车
27 760
58-63 760

**Comment by bmybgm** [comment]
五公司新五和新七车队路牌看下，谢谢

**Comment by bmybgm** [comment]
加车数量也写下

**Comment by Fangml718** [comment]
> 五公司新五和新七车队路牌看下，谢谢

| 线路    | 正路牌 | 加路牌 |
|-------|-----|-----|
| 04    | 6   | 4   |
| 110   | 17  | 7   |
| 1208  | 2   | 1   |
| 187   | 11  | 4   |
| 206   | 18  | 5   |
| 551   | 18  | 0   |
| 833   | 2   | 2   |
| 845   | 16  | 5   |
| 95    | 30  | 5   |
| 98    | 9   | 1   |
| 宝山22路 | 3   | 2   |
| 165   | 18  | 2   |
| 528   | 23  | 4   |
| 702   | 18  | 3   |
| 705   | 15  | 3   |
| 741   | 20  | 3   |
| 745   | 9   | 2   |
| 832   | 3   | 3   |
| 850   | 12  | 2   |
| 862   | 11  | 3   |
| 877   | 2   | 0   |
| 879   | 2   | 0   |
| 宝山20路 | 3   | 1   |
| 宝山37路 | 4   | 0   |

**Comment by bmybgm** [comment]
> 

502正班12？

**Comment by Fangml718** [comment]
> > 
> 
> 502正班12？

10+4

**Comment by bmybgm** [comment]
今天二公司南浦南站车队各多少路牌

**Comment by Fangml718** [comment]
> 今天二公司南浦南站车队各多少路牌

今天所有线路都按照周末路牌
| 线路     | 路牌 |
|--------|----|
| 109    | 10 |
| 171    | 14 |
| 205    | 14 |
| 43     | 18 |
| 89     | 19 |
| 闵行58路  | 4  |
| 1252   | 2  |
| 150    | 11 |
| 162    | 9  |
| 180    | 9  |
| 729    | 15 |
| 747    | 22 |
| 763    | 14 |
| 830    | 20 |
| 古美环线   | 6  |
| 虹桥枢纽1路 | 10 |
| 闵行22路  | 7  |

**Comment by bmybgm** [comment]
> 

205晚上间隔不正常，不会是有2个路牌没出或只出了早班？

**Comment by Fangml718** [comment]
> 205晚上间隔不正常，不会是有2个路牌没出或只出了早班？

14出14，至于是不是只出了早班这个看不出来

**Comment by bmybgm** [comment]
89也是今天实际出19？如果是的话，那看上去十有八九89也是有只出了早班，晚班实际翘掉的情况

**Comment by Fangml718** [comment]
> 89也是今天实际出19？如果是的话，那看上去十有八九89也是有只出了早班，晚班实际翘掉的情况

也是19出19

**Comment by bmybgm** [comment]
今天素交龙吴车队和五公司二车队各多少路牌（正班+加车）

**Comment by bmybgm** [comment]
还有南浦

**Comment by bmybgm** [comment]
还有五公司四和八车队

**Comment by Fangml718** [comment]
> 今天素交龙吴车队和五公司二车队各多少路牌（正班+加车）

| 线路     | 正路牌 | 加路牌 |
|--------|-----|-----|
| 111    | 14  | 2   |
| 1210   | 3   | 0   |
| 1220   | 2   | 0   |
| 178    | 14  | 2   |
| 178大站车 | 7   | 3   |
| 192    | 4   | 0   |
| 56     | 16  | 6   |
| 56区间   | 3   | 1   |
| 770    | 13  | 10  |
| 804    | 11  | 0   |
| 820    | 7   | 0   |
| 958    | 13  | 5   |
| 109    | 10  | 0   |
| 171    | 15  | 1   |
| 205    | 14  | 5   |
| 43     | 17  | 13  |
| 89     | 19  | 6   |
| 闵行58路  | 4   | 0   |
| 1209   | 1   | 1   |
| 151    | 17  | 0   |
| 185    | 16  | 4   |
| 210    | 12  | 5   |
| 58     | 17  | 5   |
| 68     | 13  | 7   |
| 727    | 7   | 0   |
| 767    | 10  | 2   |
| 78     | 15  | 6   |
| 821    | 3   | 1   |
| 878    | 3   | 3   |
| 959    | 11  | 2   |
| 宝山19路  | 3   | 1   |
| 宝山38路  | 5   | 0   |
| 宝山85路  | 3   | 0   |
| 1600   | 3   | 0   |
| 1606   | 8   | 0   |
| 1610   | 3   | 0   |
| 711    | 10  | 4   |
| 841    | 8   | 0   |
| 963    | 31  | 4   |
| 宝山21路  | 15  | 3   |
| 宝山23路  | 15  | 3   |
| 宝山28路  | 2   | 1   |
| 宝山31路  | 10  | 1   |
| 宝山33路  | 3   | 1   |
| 宝山4路   | 2   | 0   |
| 宝山81路  | 5   | 0   |
| 宝山82路  | 6   | 0   |
| 宝山83路  | 2   | 0   |
| 宝山88路  | 2   | 1   |
| 宝山8路   | 18  | 3   |
| 宝山90路  | 3   | 1   |
| 508    | 6   | 0   |
| 51     | 27  | 4   |
| 719    | 12  | 0   |
| 811    | 9   | 0   |
| 883    | 11  | 0   |
| 吴淞滨江线  | 3   | 0   |
| 宝山10路  | 15  | 2   |
| 宝山25路  | 11  | 0   |
| 宝山32路  | 7   | 2   |
| 宝山5路   | 10  | 0   |
| 宝山7路   | 8   | 1   |
| 宝山86路  | 5   | 0   |
| 宝山87路  | 5   | 0   |
| 宝山89路  | 3   | 0   |
| 宝山91路  | 7   | 0   |
| 宝山95路  | 7   | 0   |

**Comment by bmybgm** [comment]
宝山8路双休日18？963双休日31？

**Comment by Fangml718** [comment]
> 宝山8路双休日18？963双休日31？

是的

**Comment by dyc218** [comment]
> > 今天素交龙吴车队和五公司二车队各多少路牌（正班+加车）
> 
> 线路	正路牌	加路牌
> 111	14	2
> 1210	3	0
> 1220	2	0
> 178	14	2
> 178大站车	7	3
> 192	4	0
> 56	16	6
> 56区间	3	1
> 770	13	10
> 804	11	0
> 820	7	0
> 958	13	5
> 109	10	0
> 171	15	1
> 205	14	5
> 43	17	13
> 89	19	6
> 闵行58路	4	0
> 1209	1	1
> 151	17	0
> 185	16	4
> 210	12	5
> 58	17	5
> 68	13	7
> 727	7	0
> 767	10	2
> 78	15	6
> 821	3	1
> 878	3	3
> 959	11	2
> 宝山19路	3	1
> 宝山38路	5	0
> 宝山85路	3	0
> 1600	3	0
> 1606	8	0
> 1610	3	0
> 711	10	4
> 841	8	0
> 963	31	4
> 宝山21路	15	3
> 宝山23路	15	3
> 宝山28路	2	1
> 宝山31路	10	1
> 宝山33路	3	1
> 宝山4路	2	0
> 宝山81路	5	0
> 宝山82路	6	0
> 宝山83路	2	0
> 宝山88路	2	1
> 宝山8路	18	3
> 宝山90路	3	1
> 508	6	0
> 51	27	4
> 719	12	0
> 811	9	0
> 883	11	0
> 吴淞滨江线	3	0
> 宝山10路	15	2
> 宝山25路	11	0
> 宝山32路	7	2
> 宝山5路	10	0
> 宝山7路	8	1
> 宝山86路	5	0
> 宝山87路	5	0
> 宝山89路	3	0
> 宝山91路	7	0
> 宝山95路	7	0

56 178 958这些大概什么时候加的车有印象吗？谢谢

**Comment by Fangml718** [comment]
> 
> 56 178 958这些大概什么时候加的车有印象吗？谢谢

56和178是2月20号开始分别加1车，958从3月17号开始加2车

**Comment by Fangml718** [comment]
> 目前五公司二和五车队各多少正班和加车，谢谢

| 线路    | 正路牌 | 加路牌 |
|-------|-----|-----|
| 1209  | 1   | 1   |
| 151   | 17  | 0   |
| 185   | 16  | 4   |
| 210   | 12  | 5   |
| 58    | 17  | 5   |
| 68    | 13  | 7   |
| 727   | 7   | 0   |
| 767   | 10  | 2   |
| 78    | 15  | 6   |
| 821   | 3   | 1   |
| 878   | 3   | 3   |
| 959   | 11  | 2   |
| 宝山19路 | 3   | 1   |
| 宝山38路 | 5   | 0   |
| 宝山85路 | 3   | 0   |
| 04    | 6   | 4   |
| 110   | 17  | 7   |
| 1208  | 2   | 1   |
| 187   | 11  | 4   |
| 206   | 18  | 5   |
| 551   | 18  | 0   |
| 833   | 2   | 2   |
| 845   | 16  | 5   |
| 95    | 30  | 5   |
| 98    | 9   | 1   |
| 宝山22路 | 3   | 2   |

**Comment by bmybgm** [comment]
今天五公司十一车队各多少路牌（正+加），另外十一车队内部配车调整，但似乎户口没动？

**Comment by bmybgm** [comment]
502是11+3？159是25+4？547，813，929,730,138正+加看下，谢谢

**Comment by Fangml718** [comment]
> 今天五公司十一车队各多少路牌（正+加），另外十一车队内部配车调整，但似乎户口没动？

| 线路    | 正路牌 | 加路牌 |
|-------|-----|-----|
| 1602  | 5   | 3   |
| 1603  | 8   | 0   |
| 1607  | 7   | 0   |
| 1609  | 2   | 1   |
| 172   | 18  | 2   |
| 834   | 2   | 0   |
| 839   | 7   | 0   |
| 宝山12路 | 2   | 0   |
| 宝山13路 | 1   | 0   |
| 宝山14路 | 5   | 0   |
| 宝山15路 | 14  | 2   |
| 宝山16路 | 12  | 2   |
| 宝山18路 | 8   | 0   |
| 宝山2路  | 9   | 1   |
| 宝山30路 | 6   | 0   |
| 宝山3路  | 9   | 1   |
| 宝山6路  | 14  | 1   |
| 宝山84路 | 3   | 0   |
| 宝山92路 | 7   | 0   |
| 宝山93路 | 6   | 0   |
| 宝山9路  | 4   | 0   |

**Comment by Fangml718** [comment]
> 502是11+3？159是25+4？547，813，929,730,138正+加看下，谢谢

| 线路  | 正路牌 | 加路牌 |
|-----|-----|-----|
| 502 | 11  | 3   |
| 159 | 25  | 4   |
| 547 | 12  | 1   |
| 813 | 23  | 1   |
| 929 | 23  | 4   |
| 730 | 20  | 4   |
| 138 | 12  | 2   |

**Comment by Fangml718** [comment]
> 今天五公司十一车队各多少路牌（正+加），另外十一车队内部配车调整，但似乎户口没动？

户口没动

**Comment by bmybgm** [comment]
547目前工作日路牌多少（加车还是1个）？闵行29工作日多少加车，多少正班？沪松工作日路牌13？116工作日加车5个？

**Comment by Fangml718** [comment]
> 547目前工作日路牌多少（加车还是1个）？闵行29工作日多少加车，多少正班？沪松工作日路牌13？116工作日加车5个？

547昨日12+1，闵29昨日10+3，沪松昨日9+4（6号减到13，9号加回14，本周一开始又减到13），116昨日29+1

**Comment by bmybgm** [comment]
目前五公司五车队工作日路牌多少，其中加车多少

**Comment by Fangml718** [comment]
> 目前五公司五车队工作日路牌多少，其中加车多少

| 线路    | 正路牌 | 加路牌 |
|-------|-----|-----|
| 04    | 6   | 4   |
| 110   | 17  | 7   |
| 1208  | 2   | 1   |
| 187   | 11  | 4   |
| 206   | 18  | 5   |
| 551   | 18  | 0   |
| 833   | 2   | 2   |
| 845   | 16  | 5   |
| 95    | 30  | 5   |
| 98    | 9   | 1   |
| 宝山22路 | 3   | 2   |

**Comment by bmybgm** [comment]
43 89目前多少正多少加

**Comment by Fangml718** [comment]
> 43 89目前多少正多少加

43路17+12
89路19+6
